export default {
  IMPORT_LOTOFACIL: "IMPORT_LOTOFACIL",
  LOAD_LOTOFACIL: "LOAD_LOTOFACIL",
  GET_JOGO_LOTOFACIL: "GET_JOGO_LOTOFACIL",
  LOAD_STATISTICS: "LOAD_STATISTICS",
  GET_STATISTICS: "GET_STATISTICS"
};
